### Matrix decompositions are methods that reduce a matrix into constituent parts that make it easier to calculate more complex matrix operations.

## LU Decomposition

In [2]:
# The LU decomposition is for square matrices and decomposes 
# a matrix into L and U components.
# A = L.U (square matrix)

from numpy import array
from scipy.linalg import lu
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.00000000e+00 8.00000000e+00 9.00000000e+00]
 [0.00000000e+00 8.57142857e-01 1.71428571e+00]
 [0.00000000e+00 0.00000000e+00 1.11022302e-16]]


## QR Decomposition

In [3]:
# The QR decomposition is for n x m matrices 
# (not limited to square matrices) and decomposes
# a matrix into Q and R components.
# A = Q.R (rectangle matrix)

from numpy import array
from numpy.linalg import qr

A = array([
    [1, 2],
    [3, 4]
])

# factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)

[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
[[1. 2.]
 [3. 4.]]


## Cholesky Decomposition

In [5]:
# The Cholesky decomposition is for square symmetric matrices 
# where all values are greater than zero, so-called positive definite matrices.
# A = L.LT

from numpy import array
from numpy.linalg import cholesky

A = array([
    [2, 1, 1],
    [1, 2, 1],
    [1, 1, 2]
])
# factorize
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
