Matrix decompositions are a useful tool for reducing a matrix to their constituent parts in order to simplify a range of more complex operations. 

Perhaps the most used type of matrix decomposition is the eigendecomposition that decomposes a matrix into eigenvectors and eigenvalues.

## Eigendecomposition of a Matrix
Eigendecomposition of a matrix is a type of decomposition that involves decomposing a square matrix into a set of eigenvectors and eigenvalues.

__Eigenvectors__ are unit vectors, which means that their length or magnitude is equal to 1.0.
__Eigenvalues__ are coefficients applied to eigenvectors that give the vectors their length or magnitude.


In [1]:
# Eigendecomposition
from numpy import array
from numpy.linalg import eig

A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [2]:
# Confirm eigenvector
from numpy import array
from numpy.linalg import eig

A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# factorize
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B) # [ -3.73863537  -8.46653421 -13.19443305]
C = vectors[:, 0] * values[0]
print(C) # [ -3.73863537  -8.46653421 -13.19443305]

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]
