# C4 - Numpy N-dimentional Array

In [3]:
from numpy import array

# Create array
l = [1.0, 2.0, 3.0]
a = array(l)

# Display array
print(a)
# Display array shape
print(a.shape)
# Display array type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [4]:
# Create empty array
from numpy import empty

a = empty([3,3]) # 3x3 two-dimensional array
print(a)

[[-3.10503618e+231 -3.10503618e+231  2.20673186e-314]
 [ 2.19767885e-314  2.19242174e-314  2.19709478e-314]
 [ 2.19174588e-314  2.28069797e-314  2.19457362e-314]]


In [5]:
# Create zero array
from numpy import zeros

a = zeros([3,5]) # 3x5 zero two-dimentional array
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# Create one array
from numpy import ones

a = ones([5]) # 5-element one-dimentional array
print(a)

[1. 1. 1. 1. 1.]


# Combining Arrays

## Vertical Stack

In [9]:
# Create array with vstack
from numpy import array
from numpy import vstack

# Create first array
a1 = array([1,2,3])
# Create second array
a2 = array([4,5,6])

# Vertical stack
a3 = vstack((a1, a2)) # 2x3 two-dimentional array
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Horizontal Stack

In [10]:
# Create array with hstack
from numpy import array
from numpy import hstack

a1 = array([1,2,3])
a2 = array([4,5,6])

# Create horizontal stack
a3 = hstack((a1, a2)) # new one-dimentional array
print(a3)
print(a3.shape)

[1 2 3 4 5 6]
(6,)
