# C5 - Index, Slice and Reshape NumPy Arrays

## List to Array

In [2]:
# Create one-dimentional array
from numpy import array

# list of data
data = [11, 22, 33, 44, 55]
print(type(data))

# array of data
data = array(data)
print(data)
print(type(data))

<class 'list'>
[11 22 33 44 55]
<class 'numpy.ndarray'>


In [3]:
# Create two-dimentional array
from numpy import array

# list of data
data = [[11,22], [33, 44], [55, 66]]
print(type(data))

# array of data
data = array(data)
print(data)
print(type(data))

<class 'list'>
[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


## Array Indexing

In [4]:
# Index a one-dimentional array
from numpy import array

data = array([11, 22, 33, 44, 55])

# index data
print(data[0])
print(data[4])

11
55


In [10]:
# Index array out of bounds
from numpy import array

data = array([11, 22, 33, 44, 55])
print(data[-1]) # 55
print(data[5])  # IndexError: index 5 is out of bounds for axis 0 with size 5 

55


IndexError: index 5 is out of bounds for axis 0 with size 5

In [12]:
# Two dimentional indexing
from numpy import array

data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])

print(data[0,0]) #11

# Get the first row
print(data[0,]) # [11 22]

11
[11 22]


## Array Slicing

In [15]:
# Slice a one-dimentional array
from numpy import array

data = array([11, 22, 33, 44, 55])
print(data[:]) # print all elements in the array

[11 22 33 44 55]


In [18]:
# Slice a subset of a one-dimentional array
from numpy import array

data = array([11, 22, 33, 44, 55])
print(data[0:1]) # [11]
print(data[-2:]) ## [44 55]

[11]
[44 55]


In [20]:
# Split input and output data
from numpy import array

data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])

# Separate data
X, y = data[:, :-1], data[:, -1] # : row index and :-1 column index
print(X) # 2D array
print(y) # [33 66 99] - 1D array

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [21]:
# Split train and test data
from numpy import array

data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])

# Separate data
split = 2
train, test = data[:split, :], data[split:, :]
print(train) # [[11 22 33]
             #  [44 55 66]]
print(test)  # [[77 88 99]]

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [22]:
# Shape of one-dimentional array
from numpy import array

data = array([11, 22, 33, 44, 55])
print(data.shape) # (5, )

(5,)


In [23]:
# Shape of a two-dimentional array
from numpy import array

data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
print(data.shape) # (3, 2)

(3, 2)


In [24]:
# Row and column shape of two-dimentional array
from numpy import array

data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])

print('Rows: %d' % data.shape[0]) # 3
print('Cols: %d' % data.shape[1]) # 2

Rows: 3
Cols: 2


In [27]:
# Reshape 1D array to 2D
from numpy import array

data = array([11, 22, 33, 44, 55]) # 1 row and 5 columns
print(data)
print(data.shape) # (5, )

# Reshape
data = data.reshape((data.shape[0], 1)) # 5 rows and 1 column
print(data)
print(data.shape) # (5, 1)

[11 22 33 44 55]
(5,)
[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [28]:
# Reshape 2D array to 3D
from numpy import array

data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
print(data.shape) # (3, 2)

# Reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data)
print(data.shape) # (3, 2, 1)

(3, 2)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
(3, 2, 1)
