## Expected Value and Mean
In probability, the average value of some random variable X is called the expected value or the expectation. The expected value uses the notation E with square brackets around the name of the variable; for example:

E[X]

In [2]:
# vector mean
from numpy import array
from numpy import mean
v = array([1, 2, 3, 4, 5, 6])

# calculate mean
result = mean(v)
print(result) # 3.5

3.5


In [3]:
# matrix means
from numpy import array
from numpy import mean

M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])

# column means
col_mean = mean(M, axis = 0)
print(col_mean)
# row means
row_mean = mean(M, axis = 1)
print(row_mean)

[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


## Variance and Standard Deviation
In probability, the variance of some random variable X is a measure of how much values in the distribution vary on average with respect to the mean. The variance is denoted as the function Var() on the variable.

Var[X] = E[(X - E[X])^2] 

In [4]:
# vector variance
from numpy import array
from numpy import var

v = array([1, 2, 3, 4, 5, 6])
# calculate variance
result = var(v, ddof=1)
print(result)

3.5


In [5]:
# matrix variances
from numpy import array
from numpy import mean

M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])

# column variance
col_var = var(M, ddof=1, axis=0)
print(col_var)
# row variance
row_var = var(M, ddof=1, axis=1)
print(row_var)

[0. 0. 0. 0. 0. 0.]
[3.5 3.5]


The standard deviation is calculated as the square root of the variance and is denoted as lowercase s.

In [6]:
# matrix standard deviation
from numpy import array 
from numpy import std

M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])

# column standard deviations
col_std = std(M, ddof=1, axis=0)
print(col_std)
# row standard deviations
row_std = std(M, ddof=1, axis=1)
print(row_std)

[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]


## Covariance and Correlation