# Types of Matrices

## 1. Square Matrix

In [1]:
# A square matrix is a matrix where the number of rows (n) 
# is equivalent to the number of columns (m)

## 2. Symmetric Matrix

In [3]:
# A symmetric matrix is a type of square matrix 
# where the top-right triangle is the same as the bottom-left triangle

# A = [
#     [1 2 3 4 5],
#     [2 1 2 3 4],
#     [3 2 1 2 3],
#     [4 3 2 1 2],
#     [5 4 3 2 1]
# ]

# M = MT (Equal to its own transpose)

## 3. Triangular Matrix

In [4]:
# A triangular matrix is a type of square matrix that has all values 
# in the upper-right or lower-left of the matrix with 
# the remaining elements filled with zero values.

# A = [
#     [1 2 3],
#     [0 1 2],
#     [0 0 3],
# ]

# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu

M = array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])

# lower triangle matrix
lower = tril(M)
print(lower) # [[1 0 0]
             #  [1 2 0]
             #  [1 2 3]]

# upper triangular matrix
upper = triu(M)
print(upper) # [[1 2 3]
             #  [0 2 3]
             #  [0 0 3]]

[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


## 4. Diagonal Matrix

In [5]:
# A diagonal matrix is one where values outside of the main diagonal 
# have a zero value, where the main diagonal is taken from the top left 
# of the matrix to the bottom right. A diagonal matrix

# Diagonal matrix
from numpy import array
from numpy import diag

M = array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])

# Extract diagonal vector
d = diag(M) # [1 2 3]
print(d)
# Create diagonal matrix from vector
D = diag(d)
print(D) # [[1 0 0]
         #  [0 2 0]
         #  [0 0 3]]

[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


## 5. Identity Matrix

In [7]:
# An identity matrix is a matrix that does not change 
# any vector when we multiply that vector by that matrix.

# Identify matrix
from numpy import identity
I = identity(3)
print(I) # [[1. 0. 0.]
         #  [0. 1. 0.]
         #  [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 6. Orthogonal Matrix

In [8]:
# Two vectors are orthogonal when their dot product equals zero. 
# The length of each vector is 1 then the vectors are called o
# rthonormal because they are both orthogonal and normalized.

# QT * Q = Q * QT = I (transpose)

from numpy import array
from numpy.linalg import inv

Q = array([
    [1, 0],
    [0, -1]
])

# Inverse equivalence
V = inv(Q)
print(Q.T) # [[ 1  0]
           #  [ 0 -1]]
print(V) # [[ 1.  0.]
         #  [-0. -1.]]

# Identity equivalence
I = Q.dot(Q.T)
print(I) # [[1 0]
         #  [0 1]]

[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]
