## Transpose

In [2]:
# The Transpose operation for flipping the dimensions of a matrix.
# A defined matrix can be transposed, which creates a new matrix with the number of columns
# and rows flipped
from numpy import array

A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Calculate transpose
C = A.T
print(C) # [[1 3 5]
         #  [2 4 6]]

[[1 3 5]
 [2 4 6]]


## Inverse

In [3]:
# The Inverse operations used in solving systems of linear equations.
# Matrix inversion is a process that finds another matrix that when multiplied with the matrix,
# results in an identity matrix
from numpy import array
from numpy.linalg import inv

A = array([
    [1.0, 2.0],
    [3.0, 4.0]
])

# invert matrix
B = inv(A)
print(B) # [[-2.   1. ]
         #  [ 1.5 -0.5]]

# multiply A and B
I = A.dot(B)
print(I) # [[1.0000000e+00 0.0000000e+00] # float 
         #  [8.8817842e-16 1.0000000e+00]]

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## Trace

In [5]:
# A trace of a square matrix is the sum of the values on the main diagonal of the matrix 
# (top-left to bottom-right)
# tr(A) =A[0,0] +A[1,1] +A[2,2]

from numpy import array
from numpy import trace

A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Calculate trace
B = trace(A)
print(B) # 15 = 1 + 5 + 9

15


## Determinant

In [6]:
# The determinant of a square matrix is a scalar representation of the volume of the matrix.
from numpy import array
from numpy.linalg import det

A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Calculate determinant
B = det(A)
print(B)  # 6.66133814775094e-16 - should be 0

6.66133814775094e-16


## Rank

In [8]:
# The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix
# An intuition for rank is to consider it the number of dimensions spanned by all of the vectors
# within a matrix
from numpy import array
from numpy.linalg import matrix_rank

# rank
v1 = array([1, 2, 3])
vr1 = matrix_rank(v1)
print(vr1) # 1

# zero rank
v2 = array([0, 0, 0, 0, 0])
vr2 = matrix_rank(v2)
print(vr2) # 0

1
0


In [14]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank

# rank 0
M0 = array([
    [0, 0],
    [0, 0]
])
print(matrix_rank(M0)) # 0

# rank 1
M1 = array([
    [1, 2],
    [1, 2]
])
print(matrix_rank(M1)) # 1

# rank 2
M2 = array([
    [1, 2],
    [3, 4]
])
print(matrix_rank(M2)) # 2

0
1
2
