In [1]:
# Define a matrix
from numpy import array 

A = array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A) # 2x3 matrix

[[1 2 3]
 [4 5 6]]


In [2]:
# Matrix addition
from numpy import array

A = array([
    [1, 2, 3],
    [4, 5, 6]
])

B = array([
    [1, 2, 3],
    [4, 5, 6]
])

# Add matrices
C = A + B
print(C) # [[ 2  4  6]
         #  [ 8 10 12]]

[[ 2  4  6]
 [ 8 10 12]]


In [3]:
# Matrix substraction
from numpy import array

A = array([
    [1, 2, 3],
    [4, 5, 6]
])

B = array([
    [0.5, 0.5, 0.5],
    [0.5, 0.5, 0.5]
])

# Substract matrices
C = A - B
print(C) # [[0.5 1.5 2.5]
         #  [3.5 4.5 5.5]]

[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [4]:
# Matrix multiplication (Hadamard Product)
from numpy import array

A = array([
    [1, 2, 3],
    [4, 5, 6]
])

B = array([
    [1, 2, 3],
    [4, 5, 6]
])

# multiply matrices
C = A * B
print(C) # [[ 1  4  9]
         #  [16 25 36]]

[[ 1  4  9]
 [16 25 36]]


In [5]:
# Matrix division
from numpy import array

A = array([
    [1, 2, 3],
    [4, 5, 6]
])

B = array([
    [1, 2, 3],
    [4, 5, 6]
])

# Divide matrices
C = A / B
print(C) # [[1. 1. 1.]
         #  [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# Matrix-Matrix Multiplication (Matrix dot product)
# Rule: The number of columns (n) in the first matrix (A) 
# must equal the number of rows (m) in the second matrix (B).

from numpy import array

A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = array([
    [1, 2],
    [3, 4]
])

# Mutiply matrix
C = A.dot(B)
print(C) # [[ 7 10]
         #  [15 22]
         #  [23 34]]

# Mltiply matrix with @ operator
D = A @ B
print(D) # [[ 7 10]
         #  [15 22]
         #  [23 34]]

[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


In [7]:
# Matrix-Vector Multiplication
# Rule: the number of columns in the matrix must equal 
# the number of items in the vector
from numpy import array

A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = array([0.5, 0.5])

# Multiply
C = A.dot(B)
print(C) # [1.5 3.5 5.5]

[1.5 3.5 5.5]


In [8]:
# Matrix-scalar multiplication
from numpy import array 

A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])

b = 0.5

# Multiply
C = A * b
print(C) # [[0.5 1. ]
         #  [1.5 2. ]
         #  [2.5 3. ]]

[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
