In [1]:
# Create a vector
from numpy import array

# define vector
v = array([1, 2, 3])
print(v) # [1 2 3]

[1 2 3]


In [2]:
# Vector addition
from numpy import array

a = array([1, 2, 3])
b = array([1, 2, 3])

# Add vectors
c = a + b
print(c) # [2 4 6]

[2 4 6]


In [3]:
# Vector substraction
from numpy import array

a = array([1, 2, 3])
b = array([0.5, 0.5, 0.5])

# Substract vectors
c = a - b
print(c) # [0.5 1.5 2.5]

[0.5 1.5 2.5]


In [4]:
# Vector multiplication
from numpy import array

a = array([1, 2, 3])
b = array([1, 2, 3])

# Multiply vectors
c = a * b
print(c) # [1 4 9]

[1 4 9]


In [5]:
# Vector division
from numpy import array

a = array([1, 2, 3])
b = array([1, 2, 3])

# Divide vectors
c = a / b
print(c) # [1. 1. 1.]


[1. 1. 1.]


In [6]:
# Vector dot product
from numpy import array

a = array([1, 2, 3])
b = array([1, 2, 3])

# Dot product
c = a.dot(b) # 1*1 + 2*2 + 3*3
print(c) # 14

14


In [7]:
# Vector scalar multiplication
from numpy import array

a = array([1, 2, 3])
s = 0.5

# Scalar multiplication
c = s * a
print(c) # [0.5 1.  1.5]

[0.5 1.  1.5]
